import { useQuery } from "@tanstack/react-query";
import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

import type { Product } from "~/types/products.types";


const Home: NextPage = () => {

  // this is for your reference only, you can change it to whatever you want
  const { data, isLoading } = useQuery<Product[]>(['products'], async () => {
    const res = await fetch('https://fakestoreapi.com/products')
    return res.json()
  })


  return (
    <>
      <Head>
        <title>NextGenX E-commerce</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="mb-4 text-4xl text-center text-gray-800 font-bold font-sans">
        NextGenX E-commerce
      </h1>
      <p className="text-sm text-center text-gray-600 font-sans">
        Get started here
      </p>

        {isLoading ? (
          <>Loading...</>
        ): (
          <div>
            {data?.map((product) => (
              <div key={product.id}>
                <Image width={200} height={200} src={product.image} alt={product.title} />
                <h1>{product.title}</h1>
              </div>
            ))}
          </div>
        )}

      
      

    </>
  );
};

export default Home;
