import { type NextPage } from "next";
import Head from "next/head";
import Header from "~/components/Header";
import ProductComponent from "~/components/home/ProductComponent ";
import { useSelector, useDispatch } from "react-redux";
import { AppDispatch, RootState } from "~/app/store";

import type { Product as ProductType } from "~/types/products.types";
import { useEffect, useRef } from "react";
import { fetchItems } from "~/app/slices/itemSlice";


const Home: NextPage = () => {
  const tracking = useRef(true)
  const { items } = useSelector((state: RootState) => state.items)
  const dispatch = useDispatch<AppDispatch>()
  useEffect(() => {
    if (tracking.current) {
      dispatch(fetchItems())
    }
    return () => {
      tracking.current = false
    }
  }, [])
  return (
    <>
      <Head>
        <title>NextGenX E-commerce</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      {items.length < 1 ? (
        <>Loading...</>
      ) : (
        <div className='flex justify-start gap-2 flex-wrap p-3'>
          {items?.map((item: ProductType) => (
            <ProductComponent key={item.id} product={item} />
          ))}
        </div>
      )}

    </>
  );
};
export default Home;