import { useQuery } from "@tanstack/react-query";
import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Header from "~/components/Header";
import ProductComponent  from "~/components/home/ProductComponent ";

import type { Product as ProductType } from "~/types/products.types";

const Home: NextPage = () => {
  // this is for your reference only, you can change it to whatever you want
  const { data, isLoading } = useQuery<ProductType[]>(['products'], async () => {
    const res = await fetch('https://fakestoreapi.com/products')
    return res.json();
  })


  return (
    <>
      <Head>
        <title>NextGenX E-commerce</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      {isLoading ? (
        <>Loading...</>
      ) : (
        <div className='flex justify-start gap-2 flex-wrap p-3'>
          {data?.map((product) => (
            <ProductComponent key={product.id} itemType={product} />
            ))}
        </div>
      )}




    </>
  );
};
export default Home;